name: lolipop_book_store
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  cloud_firestore: ^0.12.9+5
  flutter_launcher_icons: ^0.7.4
  simple_animations: ^1.3.7
  page_transition: ^1.1.5
  datetime_picker_formfield: ^1.0.0
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  google_sign_in: ^4.1.0
  fluttertoast: ^3.1.3
  email_validator: "^1.0.0"
  flutter_facebook_login: ^2.0.0
  cached_network_image: ^2.0.0
  flutter_blurhash: ^0.1.2
  bubble_tab_indicator: ^0.1.4
  separated_number_input_formatter: 0.0.2
  pin_code_fields: 2.4.0
  awesome_dialog: ^0.1.3
  custom_radio_grouped_button: ^1.0.0
  momo_payment_plugin: ^0.0.1+1
  ntp: ^1.0.5
  string_validator: ^0.1.4
  random_string: ^2.0.1
  animated_dialog_box: ^0.0.2
  tiengviet: ^0.3.0
  webview_flutter: ^0.3.19+9
  flutter_spinning_wheel: ^1.1.0
  # Tab
  built_tab_navigator: ^0.2.0
  # Floating action button Speed dial
  flutter_speed_dial: ^1.2.5
  shared_preferences: ^0.5.4+9
  # Rating Bar
  flutter_rating_bar: ^3.0.1+1
  #Loading skeleton
  skeleton_text: ^1.0.0
  #Direct Select
  direct_select: "^1.0.0"
  #Datepicker
  flutter_rounded_date_picker: ^1.0.4
  #onboarding
  introduction_screen: ^1.0.7
  #dropdown
  material_dropdown_formfield: ^0.1.0
  flutter_dialogs: ^1.0.3
  keyboard_dismisser: ^1.0.2
  intl: ^0.16.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "images/logo/logo.png"
  image_path_ios: "images/logo/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/carousel/carousel1.jpg
    - images/carousel/carousel2.jpg
    - images/carousel/carousel3.jpg
    - images/logo/logo.png
    - images/logo/logoGoogle.png
    - images/logo/logoFacebook.jpg
    - images/background/welcome.jpg
    - images/background/otp_verification.png
    - images/background/background_getTime.jpg
    - images/categories/blockchain.jpeg
    - images/categories/chuyennganh.jpg
    - images/categories/giaokhoagiaotrinh.jpg
    - images/categories/kinhte.jpg
    - images/categories/ngoaivan.jpg
    - images/categories/phattrienbanthan.png
    - images/categories/tapchi.jpg
    - images/categories/thieunhi.jpg
    - images/categories/thuongthucdoidong.jpg
    - images/categories/tinhoc.jpg
    - images/categories/vhnuocngoai.png
    - images/categories/vhtrongnuoc.png
    - images/introduce/introduce1.png
    - images/introduce/introduce2.png
    - images/introduce/introduce3.png
    - images/introduce/introduce4.png
    - images/user/icon_female.png
    - images/user/icon_male.png
    - images/icon/iconwheel.png
    - images/rotation/roll.png
    - images/rotation/roll_point.png
    - images/icon/promo_code.png
    - images/background/promocode.jpg
    - images/background/profile_background.png
    - images/background/empty_cart_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf
    - family: AlfaSlabOne-Regular
      fonts:
        - asset: fonts/AlfaSlabOne-Regular.ttf
    - family: Lora
      fonts:
        - asset: fonts/Lora-Regular.ttf
    #        - asset: fonts/Lora-Bold.ttf
    - family: BungeeInline-Regular
      fonts:
        - asset: fonts/BungeeInline-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
